### ISSUE TITLE
Variable mutation gif confusability

### ISSUE THREAD

**Issue by flyswatter** [maxogden/javascript-for-cats#34]
As I [commented in a somewhat-related PR I made](https://github.com/maxogden/javascript-for-cats/pull/33#issuecomment-74891338), I increasingly think the gif in the `Functions` section should have one of two changes:
 - Don't do the part where you show the string isn't changed
 - Put the gif after the explanation that the function does not change the variable.

Showing them this gif before they expect an unchanged string has a chance of throwing them into that rabbit hole.

**Comment by maxogden** [comment]
I think showing that the original value is unmodified is important here, so I'd rather keep the gif unchanged and instead work on re-arranging this section

**Comment by flyswatter** [comment]
I can understand that perspective.
