### ISSUE TITLE
Standard way of looping is not mentioned at all.

### ISSUE THREAD

**Issue by SanketDG** [maxogden/javascript-for-cats#35]
`Underscore.js` is great for doing stuff, but they are generally introduced at an intermediate stage of learning. But it's great that you mentioned the `times` function, it's probably good to have it there.

But not without `for` and `while`. I couldn't help but ask why would you not point out the standard way of looping that has been used, like forever. I understand using the `times` function is way easier for cats, but if they will learn js, they better learn it properly the first time before moving onto deeper aspects.

I think they should have a place in the tutorial. Thoughts?

**Comment by SanketDG** [comment]
@maxogden ping.

**Comment by justinjhendrick** [comment]
I agree, `for` and `while` should be mentioned. Even if it's briefly as an alternative to the functional style of `_.times`.
